fafranco82/swdestinydb-json-data

schema/card_schema.json, schema/card_schema_trans.json, validate.py
I adjusted the card schema and fixed up validation script.
the card schema changes should be fairly straightforward, but a few words on the validation script changes:
- I took out cycle validation, since this is a concept that does not seem to exist (at the moment)
- "packs" have been replaced by "sets".
running the validation script works now, but it reveals two data errors in the set data - both cards ("Admiral Ackbar" and "Padme Amidala) have the correct values on the swdestinydb.com.
anyhow, i hope this holds up. please review, thanks.
=> Updated validate.py and card schema

set/AW.json
=> cost fix for underworld connections

set/AW.json
=> typo fixed

README.md, schema/card_schema.json, set/AW.json
This will be teamed up with a pull request on the application repo as well.
=> Updated data to add TableTop Simulator CardID

translations/it/affiliations.json, translations/it/factions.json, translations/it/rarities.json, translations/it/set/AW.json, translations/it/sets.json, translations/it/sideTypes.json, translations/it/subtypes.json, translations/it/types.json
JSON data IT-translation is done.
Need to validate files, though. I leave this issue to you, guys.
=> JSON files IT-translation done.

translations/fr/affiliations.json, translations/fr/rarities.json, translations/fr/set/AW.json, translations/fr/sets.json, translations/fr/sideTypes.json, translations/fr/subtypes.json, translations/fr/types.json
=> French translation

translations/it/set/AW.json
Correction for "Second Chance" ita translation
=> Klark d it translation

set/SoR.json
When I added all the cards today at swdestinydb.com, I found some typos and other issues with the pull request I made yesterday  #23 . This pull request fixes those issues that I found.
=> Fixed typos and some other issues with the SoR pre release cards

set/SoR.json
[51] - Supply Line
[85] One-Quarter Portion
[136] Evade
=> Pre-release pulls added

translations/it/set/SoR.json
I added emphatized text in order to clarify this is unofficial. When i'll get the real cards i'll start official translation.
=> Partial unofficial IT translation of SoR.

set/SoR.json
=> Update Krennic subtitle capitalization

translations/it/set/SoR.json
Last update with official wording directly from live cards.
Whole SoR set should be OK.
=> SoR ita translation - final

set/SoR.json
This appears to be the only missing ttscardid in the set of 160.
=> Added ttscardid to Chirrut Imwa in the SoR data set

translations/fr/set/SoR.json
This is the french translation for original french cards.
=> Add French translation for SoR

translations/zh/set/AW.json
=> translate name

set/LEG.json
https://www.youtube.com/watch?v=pNOgVqzDVMc
=> Rebel Impact spoilers 2017-12-08

set/LEG.json
3 melee damage for one resource, not ranged damage.
=> Fix Maul's die

set/LEG.json
Fixed typos for cards 75, 79, 82, 84, 85, 86, 87, 91, 109, 117, 125, 135, 138, 140, 143, 146, 153, 154, 155, 158, 159, 166, and 167
=> Fixed Typos

set/LEG.json
=> Re-fixed typos lost in previous merge

set/LEG.json
updated to reflect most recent update of sw destiny tts module - previous ttscardids are now invalid
=> final legacies ttscardids

desktop.ini, translations/it/set/LEG.json
=> LEG minor update

subtypes.json
- Remove duplicate `artillery` definition
- Re-sort by code
=> Clean up subtypes.json

translations/it/set/EaW.json, translations/it/set/LEG.json, translations/it/set/TPG.json
=> Minor updates and fixes

translations/de/cycles.json, translations/de/set/EaW.json, translations/de/set/LEG.json, translations/de/set/RIV.json, translations/de/set/TPG.json, translations/de/set/WotF.json, translations/de/sets.json, translations/de/sideTypes.json, translations/de/starterPacks.json, translations/de/subtypes.json, translations/de/types.json
Hey,
i started off with some german translations, hoping that i took the correct approach for committing the changes ...
I will try to commit more translations for the Legacies set in the near future.
Greetings
Sebastian
=> German translation

translations/de/set/LEG.json
Added translations for all cards in Legacies I personally own.
=> German translations for Legacies

set/WotF.json
Fixed 3 typos and added card IDs for Tabletop Simulator.
=> Fix typos and add TTS card IDs

cycles.json, set/AW.json, set/EaW.json, set/LEG.json, set/RIV.json, set/SoR.json, set/WotF.json
See title, not much else to say. The diff should be useful. 
FWIW, I went through each set and only found those. There could be more, but I tried to be thorough. Thanks!
=> Fix Typos + Add Date for Legacies Cycle

translations/pt/set/EAW.json, translations/pt/set/LEG.json, translations/pt/set/SOR.json, translations/pt/set/TPG.json, translations/pt/set/WOTF.json
Adding name and subtitle for portuguese language.
All of them was taken from https://mypcards.com/swdestiny, a project that I am part of.
Since we are using your data to have all the cards on our platform, this is a why to say thank you for the good work! As soon as we add portuguese description, I will create another PR.
=> Add name and subtitle for portuguese language

set/CONV.json
=> Convergence typos.

set/CONV.json
Addition of new spoilers maz and moxie.  Plus padmes ship was listed as 82, but it's actually 85.
=> Adding moxie, maz and correcting padme's ship

set/CONV.json
Correction from 2 focus to 1 focus.
=> Correct moxie

set/CONV.json
A few minor typos to Phasma, Commando Droid and Sinister Peace
=> Minor typos

set/CONV.json
=> Minor typo

set/CONV.json, set/WotF.json
Both commits involve correcting or adding information missing for the cards.
=> Spell Checking Guru

set/AoN.json
Added ttscardID 50200 through 50219 for Allies of necessity. Numbers were chosen based on Elrond's previous work on the mod.
=> Updated AoN.json to include ttscard id

set/CONV.json
Fixes https://github.com/fafranco82/swdestinydb/issues/270
#swdestinydbisloveswdestinydbislife
=> Correct rarity of Custom Bandolier in convergence set.

translations/fr/formats.json, translations/fr/set/AoN.json, translations/fr/sets.json, translations/fr/sideTypes.json, translations/fr/subtypes.json, translations/fr/types.json
- All missing keywords have been added
- Allies of Necessity set added
All sets will be added soon, but AoN being the first one without any official translation, it will be very helpful for players.
=> French translation update

set/SoH.json
Hoth Trooper color fix and Fateful companions plot affiliation fix and typo fix.
=> Updated SoH.json

set/SoH.json
Added last cards. I believe I got the formatting correct this time. ;)  Thanks for your work.
=> Added last 7 missing cards

set/SoH.json
Fixed Spark of Hope cards 126 and 129 having swapped data.  Added ttscardid field to all Spark of Hope cards.  Removed unprintable characters.
=> Fix card 126 and 129 swap and add ttscardid fields

formats.json
Added Spark of Hope to make legal (7/5)
=> Updated formats.json

set/SoH.json
=> Fix typo in Chopper's name.

set/SoH.json
Fixed 0-0-0 Protocol Matrix and Predatory Banker having swapped orders and ttscardid values.
=> Fix mixed-up cards

translations/fr/set/SoH.json
French corrections untill SoH card 074
=> French corrections untill SoH card 074

translations/fr/set/SoH.json
=> Full french corrections SoH

set/CM.json
These are the new cards spoiled in Alt Art form at Worlds 2019
=> World's Covert Missions spoilers

set/CM.json
Adding stream spoilers plus v minor Boba typo
=> More Worlds spoilers

set/CM.json
Sorry about this. Been a while since I've typed up cards and I formatted these incorrectly.
=> Fix formatting for symbols in card text

set/AW.json, set/CM.json, set/CONV.json, set/SoH.json, sets.json
- Fixed some typos in sets
- Added cgdb id for LEG and TPG
=> Fix some typos

set/CM.json
=> Merchant freighter subtype

set/CM.json
Added ttscardid fields for upcoming Super Destiny update.
=> Added ttscardid fields.

set/CM.json
was encoded as neutral. this is a hero card
=> make Valourous Tribe hero

set/TR.json
=> Clean Up Some Transformations Tags

cycles.json, formats.json
To take up less space making the website look less messy
=> Simplifying the format name

set/FA.json
Plus correcting a couple of typos
=> Adding TTS IDs and adding more spoilers

set/FA.json
The world is watching the db now.  Hopefully this is the last of the typos
=> Another FA typo... sorry and thanks Paco

schema/set_schema.json, sets.json
Please check the PR (incoming) on the main app repository for more information.
=> Feature : Add a project (group) name for community new sets

set/RM.json
And thank you @fafranco82 for cleaning up some of the issues with the old json
=> Chimaera spoilers

set/HS.json
I see you've integrated validate into the push process, which is great. This apparently failed with the error: Not a valid json. However, I ran it on a separate json validator and it works fine. So I don't know if this is a glitch, but without a more verbose error I can't work out what the problem is.  Hopefully it's all good. Cheers @fafranco82
=> More spoilers

set/HS.json
Thanks @fafranco82 for the quick merges lately. This is the last big change - I got the TTS IDs wrong so this is needed for people to play online. Cheers.
=> Correcting TTS IDs
